name: Test JS

on: [push]

jobs:
  test_js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '8', '9', '10', '11', '12' ]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node v${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm test
